name: Not Alone
description: This contains a nice description of the site.
logo: logo.png

markdown: kramdown
pygments: true

# always points to production site
canonical: https://www.notalone.gov

# any path prefix to apply, run with --baseurl="" in development
baseurl: /campus

kramdown:
  parse_block_html: true

cachebuster: '0426131729'